"""init: 全部数据表

Revision ID: e389d6fcf4d7
Revises: 
Create Date: 2026-06-10 15:48:18.056697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e389d6fcf4d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='角色ID'),
    sa.Column('role_name', sa.String(length=32), nullable=False, comment='角色名称'),
    sa.Column('permissions', sa.Text(), nullable=True, comment='权限列表（JSON格式存储）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('room_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='类型ID'),
    sa.Column('type_name', sa.String(length=32), nullable=False, comment='类型名称'),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='基础价格（元/晚）'),
    sa.Column('facility', sa.String(length=256), nullable=True, comment='配套设施（逗号分隔）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='客房ID'),
    sa.Column('room_num', sa.String(length=16), nullable=False, comment='房间号'),
    sa.Column('type_id', sa.Integer(), nullable=False, comment='所属房型ID'),
    sa.Column('floor', sa.SmallInteger(), nullable=False, comment='所在楼层'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='实际售价（元/晚）'),
    sa.Column('status', sa.String(length=16), nullable=True, comment='状态: available-空闲, occupied-已入住, reserved-已预订, maintenance-维护中'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='备注信息'),
    sa.ForeignKeyConstraint(['type_id'], ['room_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_num')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='操作员ID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录用户名'),
    sa.Column('password', sa.String(length=256), nullable=False, comment='密码（哈希存储）'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='所属角色ID'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='真实姓名'),
    sa.Column('status', sa.String(length=16), nullable=True, comment='状态: enabled-启用, disabled-禁用'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('order_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='订单ID'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作员ID（可为空，表示顾客自助预订）'),
    sa.Column('customer_name', sa.String(length=32), nullable=False, comment='客户姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='入住房间ID'),
    sa.Column('check_in', sa.DateTime(), nullable=False, comment='入住时间'),
    sa.Column('check_out', sa.DateTime(), nullable=True, comment='退房时间（NULL表示未退房）'),
    sa.Column('total_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='总费用'),
    sa.Column('renewal_count', sa.Integer(), nullable=True, comment='续费次数'),
    sa.Column('reminded', sa.Boolean(), nullable=True, comment='是否已催款提醒'),
    sa.Column('order_status', sa.String(length=16), nullable=True, comment='订单状态: pending-待确认, confirmed-已确认, completed-已完成, cancelled-已取消'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='评价ID'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='房间ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='评价人ID'),
    sa.Column('rating', sa.SmallInteger(), nullable=False, comment='评分(1-5星)'),
    sa.Column('content', sa.Text(), nullable=True, comment='评价内容'),
    sa.Column('tags', sa.String(length=256), nullable=True, comment='标签(逗号分隔)'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='评价时间'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='挂账ID'),
    sa.Column('company_name', sa.String(length=128), nullable=False, comment='挂账公司名称'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='关联订单ID（一对一）'),
    sa.Column('debt_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='挂账金额'),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='已还金额'),
    sa.Column('pay_status', sa.String(length=16), nullable=True, comment='还款状态: unpaid-未还, partial-部分, full-还清'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='挂账创建时间'),
    sa.ForeignKeyConstraint(['order_id'], ['order_record.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit')
    op.drop_table('review')
    op.drop_table('order_record')
    op.drop_table('user')
    op.drop_table('room')
    op.drop_table('room_type')
    op.drop_table('role')
    # ### end Alembic commands ###
